// This file is autogenerated by VESC Tool

#ifndef CONFXML_H_
#define CONFXML_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define DATA_REFLOATCONFIG__SIZE		23393

// Variables
extern uint8_t data_refloatconfig_[];

// CONFXML_H_
#endif
