// This file is autogenerated by VESC Tool

#ifndef CONF_DEFAULT_H_
#define CONF_DEFAULT_H_

// Angle P
#ifndef CFG_DFLT_KP
#define CFG_DFLT_KP 25
#endif

// Rate P
#ifndef CFG_DFLT_KP2
#define CFG_DFLT_KP2 0.6
#endif

// Angle I
#ifndef CFG_DFLT_KI
#define CFG_DFLT_KI 0.005
#endif

// Pitch KP
#ifndef CFG_DFLT_MAHONY_KP
#define CFG_DFLT_MAHONY_KP 1.9
#endif

// Roll KP
#ifndef CFG_DFLT_MAHONY_KP_ROLL
#define CFG_DFLT_MAHONY_KP_ROLL 1.4
#endif

// Accelerometer Confidence Decay
#ifndef CFG_DFLT_BF_ACCEL_CONFIDENCE_DECAY
#define CFG_DFLT_BF_ACCEL_CONFIDENCE_DECAY 0.02
#endif

// Angle P (Braking)
#ifndef CFG_DFLT_KP_BRAKE
#define CFG_DFLT_KP_BRAKE 0.9
#endif

// Rate P (Braking)
#ifndef CFG_DFLT_KP2_BRAKE
#define CFG_DFLT_KP2_BRAKE 0.7
#endif

// Loop Hertz
#ifndef CFG_DFLT_HERTZ
#define CFG_DFLT_HERTZ 800
#endif

// Pitch Axis Fault Cutoff
#ifndef CFG_DFLT_FAULT_PITCH
#define CFG_DFLT_FAULT_PITCH 60
#endif

// Roll Axis Fault Cutoff
#ifndef CFG_DFLT_FAULT_ROLL
#define CFG_DFLT_FAULT_ROLL 60
#endif

// ADC1 Switch Voltage
#ifndef CFG_DFLT_FAULT_ADC1
#define CFG_DFLT_FAULT_ADC1 1.5
#endif

// ADC2 Switch Voltage
#ifndef CFG_DFLT_FAULT_ADC2
#define CFG_DFLT_FAULT_ADC2 1.5
#endif

// Beep on Sensor Fault
#ifndef CFG_DFLT_IS_FOOTBEEP_ENABLED
#define CFG_DFLT_IS_FOOTBEEP_ENABLED 1
#endif

// Pitch Fault Delay
#ifndef CFG_DFLT_FAULT_DELAY_PITCH
#define CFG_DFLT_FAULT_DELAY_PITCH 400
#endif

// Roll Fault Delay
#ifndef CFG_DFLT_FAULT_DELAY_ROLL
#define CFG_DFLT_FAULT_DELAY_ROLL 400
#endif

// Half Switch Fault Delay
#ifndef CFG_DFLT_FAULT_DELAY_SWITCH_HALF
#define CFG_DFLT_FAULT_DELAY_SWITCH_HALF 250
#endif

// Full Switch Fault Delay
#ifndef CFG_DFLT_FAULT_DELAY_SWITCH_FULL
#define CFG_DFLT_FAULT_DELAY_SWITCH_FULL 250
#endif

// ADC Half State Fault ERPM
#ifndef CFG_DFLT_FAULT_ADC_HALF_ERPM
#define CFG_DFLT_FAULT_ADC_HALF_ERPM 200
#endif

// Treat Both Sensors as One (Posi)
#ifndef CFG_DFLT_FAULT_IS_DUAL_SWITCH
#define CFG_DFLT_FAULT_IS_DUAL_SWITCH 1
#endif

// Disable Moving Faults
#ifndef CFG_DFLT_FAULT_MOVING_FAULT_DISABLED
#define CFG_DFLT_FAULT_MOVING_FAULT_DISABLED 1
#endif

// Enable Darkride
#ifndef CFG_DFLT_FAULT_DARKRIDE_ENABLED
#define CFG_DFLT_FAULT_DARKRIDE_ENABLED 0
#endif

// Enable Reverse Stop
#ifndef CFG_DFLT_FAULT_REVERSESTOP_ENABLED
#define CFG_DFLT_FAULT_REVERSESTOP_ENABLED 1
#endif

// Angle
#ifndef CFG_DFLT_TILTBACK_DUTY_ANGLE
#define CFG_DFLT_TILTBACK_DUTY_ANGLE 5
#endif

// Speed
#ifndef CFG_DFLT_TILTBACK_DUTY_SPEED
#define CFG_DFLT_TILTBACK_DUTY_SPEED 3
#endif

// Duty Cycle Threshold
#ifndef CFG_DFLT_TILTBACK_DUTY
#define CFG_DFLT_TILTBACK_DUTY 0.8
#endif

// Beep on Duty Pushback
#ifndef CFG_DFLT_IS_DUTYBEEP_ENABLED
#define CFG_DFLT_IS_DUTYBEEP_ENABLED 0
#endif

// Surge Angle Increment
#ifndef CFG_DFLT_SURGE_ANGLE
#define CFG_DFLT_SURGE_ANGLE 0
#endif

// Surge Duty Cycle Start
#ifndef CFG_DFLT_SURGE_DUTY_START
#define CFG_DFLT_SURGE_DUTY_START 0.88
#endif

// Beep when Surging
#ifndef CFG_DFLT_IS_SURGEBEEP_ENABLED
#define CFG_DFLT_IS_SURGEBEEP_ENABLED 1
#endif

// Angle
#ifndef CFG_DFLT_TILTBACK_HV_ANGLE
#define CFG_DFLT_TILTBACK_HV_ANGLE 8
#endif

// Speed
#ifndef CFG_DFLT_TILTBACK_HV_SPEED
#define CFG_DFLT_TILTBACK_HV_SPEED 1
#endif

// High Voltage Threshold
#ifndef CFG_DFLT_TILTBACK_HV
#define CFG_DFLT_TILTBACK_HV 100
#endif

// Angle
#ifndef CFG_DFLT_TILTBACK_LV_ANGLE
#define CFG_DFLT_TILTBACK_LV_ANGLE 10
#endif

// Speed
#ifndef CFG_DFLT_TILTBACK_LV_SPEED
#define CFG_DFLT_TILTBACK_LV_SPEED 1
#endif

// Low Voltage Threshold
#ifndef CFG_DFLT_TILTBACK_LV
#define CFG_DFLT_TILTBACK_LV 48
#endif

// Return To Level Speed
#ifndef CFG_DFLT_TILTBACK_RETURN_SPEED
#define CFG_DFLT_TILTBACK_RETURN_SPEED 1
#endif

// Constant Tiltback
#ifndef CFG_DFLT_TILTBACK_CONSTANT
#define CFG_DFLT_TILTBACK_CONSTANT 0
#endif

// Constant Tiltback ERPM
#ifndef CFG_DFLT_TILTBACK_CONSTANT_ERPM
#define CFG_DFLT_TILTBACK_CONSTANT_ERPM 400
#endif

// Variable Tiltback Rate
#ifndef CFG_DFLT_TILTBACK_VARIABLE
#define CFG_DFLT_TILTBACK_VARIABLE 0.1
#endif

// Variable Tiltback Maximum
#ifndef CFG_DFLT_TILTBACK_VARIABLE_MAX
#define CFG_DFLT_TILTBACK_VARIABLE_MAX 0
#endif

// Variable Tiltback Start ERPM
#ifndef CFG_DFLT_TILTBACK_VARIABLE_ERPM
#define CFG_DFLT_TILTBACK_VARIABLE_ERPM 0
#endif

// Nose Angling Speed
#ifndef CFG_DFLT_NOSEANGLING_SPEED
#define CFG_DFLT_NOSEANGLING_SPEED 5
#endif

// Remote Type
#ifndef CFG_DFLT_INPUTTILT_REMOTE_TYPE
#define CFG_DFLT_INPUTTILT_REMOTE_TYPE 0
#endif

// Tiltback Angle Limit
#ifndef CFG_DFLT_INPUTTILT_ANGLE_LIMIT
#define CFG_DFLT_INPUTTILT_ANGLE_LIMIT 10
#endif

// Tiltback Speed
#ifndef CFG_DFLT_INPUTTILT_SPEED
#define CFG_DFLT_INPUTTILT_SPEED 25
#endif

// Tiltback Smoothing Factor
#ifndef CFG_DFLT_INPUTTILT_SMOOTHING_FACTOR
#define CFG_DFLT_INPUTTILT_SMOOTHING_FACTOR 1
#endif

// Invert Throttle
#ifndef CFG_DFLT_INPUTTILT_INVERT_THROTTLE
#define CFG_DFLT_INPUTTILT_INVERT_THROTTLE 1
#endif

// Input Deadband
#ifndef CFG_DFLT_INPUTTILT_DEADBAND
#define CFG_DFLT_INPUTTILT_DEADBAND 0.1
#endif

// Throttle Current Maximum
#ifndef CFG_DFLT_REMOTE_THROTTLE_CURRENT_MAX
#define CFG_DFLT_REMOTE_THROTTLE_CURRENT_MAX 0
#endif

// Grace Period
#ifndef CFG_DFLT_REMOTE_THROTTLE_GRACE_PERIOD
#define CFG_DFLT_REMOTE_THROTTLE_GRACE_PERIOD 10
#endif

// Startup Pitch Axis Angle Tolerance
#ifndef CFG_DFLT_STARTUP_PITCH_TOLERANCE
#define CFG_DFLT_STARTUP_PITCH_TOLERANCE 4
#endif

// Startup Roll Axis Angle Tolerance
#ifndef CFG_DFLT_STARTUP_ROLL_TOLERANCE
#define CFG_DFLT_STARTUP_ROLL_TOLERANCE 45
#endif

// Startup Centering Speed
#ifndef CFG_DFLT_STARTUP_SPEED
#define CFG_DFLT_STARTUP_SPEED 30
#endif

// Startup Click Current
#ifndef CFG_DFLT_STARTUP_CLICK_CURRENT
#define CFG_DFLT_STARTUP_CLICK_CURRENT 0
#endif

// Enable Simple Start
#ifndef CFG_DFLT_SIMPLESTART_ENABLED
#define CFG_DFLT_SIMPLESTART_ENABLED 0
#endif

// Enable Push Start
#ifndef CFG_DFLT_PUSHSTART_ENABLED
#define CFG_DFLT_PUSHSTART_ENABLED 0
#endif

// Enable Dirty Landings
#ifndef CFG_DFLT_DIRTYLANDINGS_ENABLED
#define CFG_DFLT_DIRTYLANDINGS_ENABLED 0
#endif

// Brake Current
#ifndef CFG_DFLT_BRAKE_CURRENT
#define CFG_DFLT_BRAKE_CURRENT 6
#endif

// I Term Limit
#ifndef CFG_DFLT_KI_LIMIT
#define CFG_DFLT_KI_LIMIT 30
#endif

// Start Angle
#ifndef CFG_DFLT_BOOSTER_ANGLE
#define CFG_DFLT_BOOSTER_ANGLE 8
#endif

// Ramp Up
#ifndef CFG_DFLT_BOOSTER_RAMP
#define CFG_DFLT_BOOSTER_RAMP 4
#endif

// Current Boost
#ifndef CFG_DFLT_BOOSTER_CURRENT
#define CFG_DFLT_BOOSTER_CURRENT 0
#endif

// Start Angle
#ifndef CFG_DFLT_BRKBOOSTER_ANGLE
#define CFG_DFLT_BRKBOOSTER_ANGLE 8
#endif

// Ramp Up
#ifndef CFG_DFLT_BRKBOOSTER_RAMP
#define CFG_DFLT_BRKBOOSTER_RAMP 4
#endif

// Current Boost
#ifndef CFG_DFLT_BRKBOOSTER_CURRENT
#define CFG_DFLT_BRKBOOSTER_CURRENT 0
#endif

// Start Current Threshold
#ifndef CFG_DFLT_TORQUETILT_START_CURRENT
#define CFG_DFLT_TORQUETILT_START_CURRENT 15
#endif

// Tilitback Angle Limit
#ifndef CFG_DFLT_TORQUETILT_ANGLE_LIMIT
#define CFG_DFLT_TORQUETILT_ANGLE_LIMIT 8
#endif

// Max Tiltback Speed
#ifndef CFG_DFLT_TORQUETILT_ON_SPEED
#define CFG_DFLT_TORQUETILT_ON_SPEED 5
#endif

// Max Tiltback Release Speed
#ifndef CFG_DFLT_TORQUETILT_OFF_SPEED
#define CFG_DFLT_TORQUETILT_OFF_SPEED 3
#endif

// Strength
#ifndef CFG_DFLT_TORQUETILT_STRENGTH
#define CFG_DFLT_TORQUETILT_STRENGTH 0
#endif

// Strength (Regen)
#ifndef CFG_DFLT_TORQUETILT_STRENGTH_REGEN
#define CFG_DFLT_TORQUETILT_STRENGTH_REGEN 0
#endif

// Strength
#ifndef CFG_DFLT_TURNTILT_STRENGTH
#define CFG_DFLT_TURNTILT_STRENGTH 0
#endif

// Tilitback Angle Limit
#ifndef CFG_DFLT_TURNTILT_ANGLE_LIMIT
#define CFG_DFLT_TURNTILT_ANGLE_LIMIT 3
#endif

// Turn Aggregate Threshold
#ifndef CFG_DFLT_TURNTILT_START_ANGLE
#define CFG_DFLT_TURNTILT_START_ANGLE 2
#endif

// ERPM Threshold
#ifndef CFG_DFLT_TURNTILT_START_ERPM
#define CFG_DFLT_TURNTILT_START_ERPM 1000
#endif

// Max Tiltback Speed
#ifndef CFG_DFLT_TURNTILT_SPEED
#define CFG_DFLT_TURNTILT_SPEED 5
#endif

// Speed Boost %
#ifndef CFG_DFLT_TURNTILT_ERPM_BOOST
#define CFG_DFLT_TURNTILT_ERPM_BOOST 200
#endif

// Speed Boost Max ERPM
#ifndef CFG_DFLT_TURNTILT_ERPM_BOOST_END
#define CFG_DFLT_TURNTILT_ERPM_BOOST_END 5000
#endif

// Turn Aggregate Target
#ifndef CFG_DFLT_TURNTILT_YAW_AGGREGATE
#define CFG_DFLT_TURNTILT_YAW_AGGREGATE 90
#endif

// ATR Uphill Strength
#ifndef CFG_DFLT_ATR_UPHILL_STRENGTH
#define CFG_DFLT_ATR_UPHILL_STRENGTH 0
#endif

// ATR Downhill Strength
#ifndef CFG_DFLT_ATR_DOWNHILL_STRENGTH
#define CFG_DFLT_ATR_DOWNHILL_STRENGTH 0
#endif

// Threshold Angle Up
#ifndef CFG_DFLT_ATR_THRESHOLD_UP
#define CFG_DFLT_ATR_THRESHOLD_UP 1.5
#endif

// Threshold Angle Down
#ifndef CFG_DFLT_ATR_THRESHOLD_DOWN
#define CFG_DFLT_ATR_THRESHOLD_DOWN 1.5
#endif

// Speed Boost
#ifndef CFG_DFLT_ATR_SPEED_BOOST
#define CFG_DFLT_ATR_SPEED_BOOST 0.3
#endif

// Tilitback Angle Limit
#ifndef CFG_DFLT_ATR_ANGLE_LIMIT
#define CFG_DFLT_ATR_ANGLE_LIMIT 8
#endif

// Max Tiltback Speed
#ifndef CFG_DFLT_ATR_ON_SPEED
#define CFG_DFLT_ATR_ON_SPEED 4
#endif

// Max Tiltback Release Speed
#ifndef CFG_DFLT_ATR_OFF_SPEED
#define CFG_DFLT_ATR_OFF_SPEED 3
#endif

// Tiltback Response Boost
#ifndef CFG_DFLT_ATR_RESPONSE_BOOST
#define CFG_DFLT_ATR_RESPONSE_BOOST 1.5
#endif

// Tiltback Transition Boost
#ifndef CFG_DFLT_ATR_TRANSITION_BOOST
#define CFG_DFLT_ATR_TRANSITION_BOOST 3
#endif

// Current Filter
#ifndef CFG_DFLT_ATR_FILTER
#define CFG_DFLT_ATR_FILTER 5
#endif

// Amps to Acceleration Ratio
#ifndef CFG_DFLT_ATR_AMPS_ACCEL_RATIO
#define CFG_DFLT_ATR_AMPS_ACCEL_RATIO 9
#endif

// Amps to Deceleration Ratio
#ifndef CFG_DFLT_ATR_AMPS_DECEL_RATIO
#define CFG_DFLT_ATR_AMPS_DECEL_RATIO 8
#endif

// Brake Tilt Strength
#ifndef CFG_DFLT_BRAKETILT_STRENGTH
#define CFG_DFLT_BRAKETILT_STRENGTH 0
#endif

// Brake Tilt Lingering
#ifndef CFG_DFLT_BRAKETILT_LINGERING
#define CFG_DFLT_BRAKETILT_LINGERING 2
#endif

// LEDs On
#ifndef CFG_DFLT_LEDS_ON
#define CFG_DFLT_LEDS_ON 1
#endif

// Headlights On
#ifndef CFG_DFLT_LEDS_HEADLIGHTS_ON
#define CFG_DFLT_LEDS_HEADLIGHTS_ON 1
#endif

// Headlights Transition
#ifndef CFG_DFLT_LEDS_HEADLIGHTS_TRANSITION
#define CFG_DFLT_LEDS_HEADLIGHTS_TRANSITION 0
#endif

// Direction Transition
#ifndef CFG_DFLT_LEDS_DIRECTION_TRANSITION
#define CFG_DFLT_LEDS_DIRECTION_TRANSITION 0
#endif

// Lights Off When Lifted
#ifndef CFG_DFLT_LEDS_LIGHTS_OFF_WHEN_LIFTED
#define CFG_DFLT_LEDS_LIGHTS_OFF_WHEN_LIFTED 1
#endif

// Status On Front When Lifted
#ifndef CFG_DFLT_LEDS_STATUS_ON_FRONT_WHEN_LIFTED
#define CFG_DFLT_LEDS_STATUS_ON_FRONT_WHEN_LIFTED 1
#endif

// Front Mode
#ifndef CFG_DFLT_LEDS_FRONT_MODE
#define CFG_DFLT_LEDS_FRONT_MODE 4
#endif

// Front Brightness
#ifndef CFG_DFLT_LEDS_FRONT_BRIGHTNESS
#define CFG_DFLT_LEDS_FRONT_BRIGHTNESS 0.5
#endif

// Front Primary Color
#ifndef CFG_DFLT_LEDS_FRONT_COLOR1
#define CFG_DFLT_LEDS_FRONT_COLOR1 4
#endif

// Front Secondary Color
#ifndef CFG_DFLT_LEDS_FRONT_COLOR2
#define CFG_DFLT_LEDS_FRONT_COLOR2 0
#endif

// Front Speed
#ifndef CFG_DFLT_LEDS_FRONT_SPEED
#define CFG_DFLT_LEDS_FRONT_SPEED 1
#endif

// Rear Mode
#ifndef CFG_DFLT_LEDS_REAR_MODE
#define CFG_DFLT_LEDS_REAR_MODE 2
#endif

// Rear Brightness
#ifndef CFG_DFLT_LEDS_REAR_BRIGHTNESS
#define CFG_DFLT_LEDS_REAR_BRIGHTNESS 0.5
#endif

// Rear Primary Color
#ifndef CFG_DFLT_LEDS_REAR_COLOR1
#define CFG_DFLT_LEDS_REAR_COLOR1 23
#endif

// Rear Secondary Color
#ifndef CFG_DFLT_LEDS_REAR_COLOR2
#define CFG_DFLT_LEDS_REAR_COLOR2 0
#endif

// Rear Speed
#ifndef CFG_DFLT_LEDS_REAR_SPEED
#define CFG_DFLT_LEDS_REAR_SPEED 1
#endif

// Headlights Mode
#ifndef CFG_DFLT_LEDS_HEADLIGHTS_MODE
#define CFG_DFLT_LEDS_HEADLIGHTS_MODE 0
#endif

// Headlights Brightness
#ifndef CFG_DFLT_LEDS_HEADLIGHTS_BRIGHTNESS
#define CFG_DFLT_LEDS_HEADLIGHTS_BRIGHTNESS 0.5
#endif

// Headlights Primary Color
#ifndef CFG_DFLT_LEDS_HEADLIGHTS_COLOR1
#define CFG_DFLT_LEDS_HEADLIGHTS_COLOR1 1
#endif

// Headlights Secondary Color
#ifndef CFG_DFLT_LEDS_HEADLIGHTS_COLOR2
#define CFG_DFLT_LEDS_HEADLIGHTS_COLOR2 0
#endif

// Headlights Speed
#ifndef CFG_DFLT_LEDS_HEADLIGHTS_SPEED
#define CFG_DFLT_LEDS_HEADLIGHTS_SPEED 1
#endif

// Taillights Mode
#ifndef CFG_DFLT_LEDS_TAILLIGHTS_MODE
#define CFG_DFLT_LEDS_TAILLIGHTS_MODE 0
#endif

// Taillights Brightness
#ifndef CFG_DFLT_LEDS_TAILLIGHTS_BRIGHTNESS
#define CFG_DFLT_LEDS_TAILLIGHTS_BRIGHTNESS 0.5
#endif

// Taillights Primary Color
#ifndef CFG_DFLT_LEDS_TAILLIGHTS_COLOR1
#define CFG_DFLT_LEDS_TAILLIGHTS_COLOR1 4
#endif

// Taillights Secondary Color
#ifndef CFG_DFLT_LEDS_TAILLIGHTS_COLOR2
#define CFG_DFLT_LEDS_TAILLIGHTS_COLOR2 0
#endif

// Taillights Speed
#ifndef CFG_DFLT_LEDS_TAILLIGHTS_SPEED
#define CFG_DFLT_LEDS_TAILLIGHTS_SPEED 1
#endif

// Status Brightness (Headlights Off)
#ifndef CFG_DFLT_LEDS_STATUS_BRIGHTNESS_HEADLIGHTS_OFF
#define CFG_DFLT_LEDS_STATUS_BRIGHTNESS_HEADLIGHTS_OFF 0.5
#endif

// Status Brightness (Headlights On)
#ifndef CFG_DFLT_LEDS_STATUS_BRIGHTNESS_HEADLIGHTS_ON
#define CFG_DFLT_LEDS_STATUS_BRIGHTNESS_HEADLIGHTS_ON 0.2
#endif

// Show Sensor Indicators While Running
#ifndef CFG_DFLT_LEDS_STATUS_SHOW_SENSORS_WHILE_RUNNING
#define CFG_DFLT_LEDS_STATUS_SHOW_SENSORS_WHILE_RUNNING 1
#endif

// Status Duty Threshold
#ifndef CFG_DFLT_HARDWARE_LEDS_STATUS_DUTY_THRESHOLD
#define CFG_DFLT_HARDWARE_LEDS_STATUS_DUTY_THRESHOLD 0.2
#endif

// Red Color Bar Percentage
#ifndef CFG_DFLT_HARDWARE_LEDS_STATUS_RED_BAR_PERCENTAGE
#define CFG_DFLT_HARDWARE_LEDS_STATUS_RED_BAR_PERCENTAGE 0.2
#endif

// Status Idle Timeout
#ifndef CFG_DFLT_HARDWARE_LEDS_STATUS_IDLE_TIMEOUT
#define CFG_DFLT_HARDWARE_LEDS_STATUS_IDLE_TIMEOUT 0
#endif

// Status Idle Mode
#ifndef CFG_DFLT_LEDS_STATUS_IDLE_MODE
#define CFG_DFLT_LEDS_STATUS_IDLE_MODE 4
#endif

// Status Idle Brightness
#ifndef CFG_DFLT_LEDS_STATUS_IDLE_BRIGHTNESS
#define CFG_DFLT_LEDS_STATUS_IDLE_BRIGHTNESS 0.3
#endif

// Status Idle Primary Color
#ifndef CFG_DFLT_LEDS_STATUS_IDLE_COLOR1
#define CFG_DFLT_LEDS_STATUS_IDLE_COLOR1 4
#endif

// Status Idle Secondary Color
#ifndef CFG_DFLT_LEDS_STATUS_IDLE_COLOR2
#define CFG_DFLT_LEDS_STATUS_IDLE_COLOR2 0
#endif

// Satus Idle Speed
#ifndef CFG_DFLT_LEDS_STATUS_IDLE_SPEED
#define CFG_DFLT_LEDS_STATUS_IDLE_SPEED 1
#endif

// LED Type
#ifndef CFG_DFLT_HARDWARE_LED_TYPE
#define CFG_DFLT_HARDWARE_LED_TYPE 0
#endif

// LED Pin
#ifndef CFG_DFLT_HARDWARE_LED_PIN
#define CFG_DFLT_HARDWARE_LED_PIN 1
#endif

// LED Color Order
#ifndef CFG_DFLT_HARDWARE_LED_COLOR_ORDER
#define CFG_DFLT_HARDWARE_LED_COLOR_ORDER 0
#endif

// Status LED Strip Length
#ifndef CFG_DFLT_HARDWARE_LEDS_STATUS_COUNT
#define CFG_DFLT_HARDWARE_LEDS_STATUS_COUNT 10
#endif

// Reverse Status LED Direction
#ifndef CFG_DFLT_HARDWARE_LEDS_STATUS_REVERSE
#define CFG_DFLT_HARDWARE_LEDS_STATUS_REVERSE 0
#endif

// Front LED Strip Length
#ifndef CFG_DFLT_HARDWARE_LEDS_FRONT_COUNT
#define CFG_DFLT_HARDWARE_LEDS_FRONT_COUNT 20
#endif

// Reverse Front LED Direction
#ifndef CFG_DFLT_HARDWARE_LEDS_FRONT_REVERSE
#define CFG_DFLT_HARDWARE_LEDS_FRONT_REVERSE 0
#endif

// Rear LED Strip Length
#ifndef CFG_DFLT_HARDWARE_LEDS_REAR_COUNT
#define CFG_DFLT_HARDWARE_LEDS_REAR_COUNT 20
#endif

// Reverse Rear LED Direction
#ifndef CFG_DFLT_HARDWARE_LEDS_REAR_REVERSE
#define CFG_DFLT_HARDWARE_LEDS_REAR_REVERSE 0
#endif

// Darkride Pitch Offset
#ifndef CFG_DFLT_DARK_PITCH_OFFSET
#define CFG_DFLT_DARK_PITCH_OFFSET 0
#endif

// Enable Beeper on Servo/PPM
#ifndef CFG_DFLT_IS_BEEPER_ENABLED
#define CFG_DFLT_IS_BEEPER_ENABLED 1
#endif

// Disable Package
#ifndef CFG_DFLT_DISABLED
#define CFG_DFLT_DISABLED 0
#endif

// Headlight and Brake Light
#ifndef CFG_SPESC_LIGHTS_MODE
#define CFG_SPESC_LIGHTS_MODE 1
#endif

// Enable EXT DC-DC
#ifndef CFG_SPESC_EXT_DCDC
#define CFG_SPESC_EXT_DCDC 1
#endif

// Idle Warning Timer
#ifndef CFG_SPESC_IDLE_TIME
#define CFG_SPESC_IDLE_TIME 0
#endif

// Enable Engine Sound
#ifndef CFG_SPESC_ENGINE_SOUND_EN
#define CFG_SPESC_ENGINE_SOUND_EN 0
#endif

// Engine Sampling Source
#ifndef CFG_SPESC_ENGINE_SAMPLE_SRC
#define CFG_SPESC_ENGINE_SAMPLE_SRC 2
#endif

// Engine Sound Volume
#ifndef CFG_SPESC_ENGINE_SOUND_VOL
#define CFG_SPESC_ENGINE_SOUND_VOL 200
#endif

// Safety Warning Sound
#ifndef CFG_SPESC_STARTUP_WARNING
#define CFG_SPESC_STARTUP_WARNING 0
#endif

// Over Speed Warning
#ifndef CFG_SPESC_SPEED_ALERT
#define CFG_SPESC_SPEED_ALERT 20
#endif

// Low Battery Warning 
#ifndef CFG_SPESC_LOW_BATTERY
#define CFG_SPESC_LOW_BATTERY 0
#endif

// CONF_DEFAULT_H_
#endif

